[workspace]
resolver = "2"
members = ["watnode"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Simon Shine", "Troels Halgreen"]
repository = "https://github.com/sshine/watmachine"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.97"
wasmtime = "31.0.0"
serde = "1.0.219"
clap = { version = "4.5.38", features = ["derive"] }

[workspace.lints.rust]


[workspace.lints.clippy]
