[package]
name = "watnode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
wasmtime.workspace = true
serde.workspace = true
clap.workspace = true